apiVersion: v1
kind: Service
metadata:
  name: t-issues
  labels:
    service: t-issues
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: t-issues
  type: LoadBalancer